name: 🧪 CI - Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  check:
    name: 🧪 Check
    uses: cyberskill-world/.github/.github/workflows/check.yml@main
