name: 🚀 CI - Deploy
on:
  workflow_run:
    workflows: ["🧪 CI - Check"]
    types:
      - completed
jobs:
  deploy:
    if: >
      github.event.workflow_run.head_branch == 'main' &&
      github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
      - name: 🔧 Setup Environment and Dependencies
        uses: cyberskill-world/.github/actions/env-deps@main
      - name: 🚧 Build project
        run: |
          pnpm build
      - name: 🔑 Configure npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
      - name: 🔗 Install semantic-release globally
        run: |
          pnpm install --global semantic-release@24.2.3 \
            @semantic-release/changelog@6.0.2 \
            @semantic-release/git@10.0.1 \
            @semantic-release/github@11.0.1 \
            @semantic-release/npm@12.0.1 \
            @semantic-release/commit-analyzer@13.0.1 \
            @semantic-release/release-notes-generator@14.0.3 \
            conventional-changelog-conventionalcommits@latest
      - name: 🔄 Merge main into release
        uses: cyberskill-world/.github/actions/merge-branch@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FROM: main
          TO: release
      - name: 🚀 Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: semantic-release
