---
name: 🚀 CI - Deploy
on:
  workflow_dispatch:
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Env & Deps
        uses: cyberskill-world/.github/actions/env-deps@2453dcc49e3e194ddfcfc88da94924acee9a8e1f # main

      - name: Build
        uses: cyberskill-world/.github/actions/build@2453dcc49e3e194ddfcfc88da94924acee9a8e1f # main

      - name: Generate SBOM
        continue-on-error: true
        run: pnpm exec cyclonedx-npm --output-format JSON --output-file bom.json

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: pnpm exec semantic-release
