name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      # ✅ Cache npm dependencies and node_modules
      - name: Cache npm dependencies and node_modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # ✅ Configure npm authentication
      - name: Configure npm authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          echo "NODE_AUTH_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV

      # ✅ Cache release dependencies separately
      - name: Cache release dependencies
        id: cache-release-deps
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: release-deps-${{ hashFiles('release-dependencies.txt') }}
          restore-keys: |
            release-deps-

      # ✅ Install release dependencies only (skip full install)
      - name: Install release dependencies
        run: |
          xargs -n 1 npm install --no-save < release-dependencies.txt

      # ✅ Release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run release
